### ISSUE TITLE
Use a single connection string

### ISSUE THREAD

**Issue by isc-rsingh** [rajrsingh/compose-grandtour-php#3]
Bring it in line with the other examples of using a single connection string.

The idea is you can set your environment variables once for all examples in whatever language.

That is going to not be quite the same for PHP of course (because it doesn’t interact with real env variables, or the command line or… anything a sane language would do :slightly_smiling_face: )… but if we can keep the template simple as COMPOSE_POSTGRESQL_URL (and PATH_TO_POSTGRESQL_CERT)…

**Comment by lornajane** [comment]
Done and the PR related is merged.  This issue can be closed
